### ISSUE TITLE
set_session cannot be used inside a transaction

### ISSUE THREAD

**Issue by mikeshultz** [mikeshultz/rawl#3]
Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/rawl-0.2.0b1-py3.6.egg/rawl/__init__.py", line 53, in __enter__
        self.conn.set_session(isolation_level=ISOLATION_LEVEL_READ_COMMITTED)
    psycopg2.ProgrammingError: set_session cannot be used inside a transaction

**Comment by mikeshultz** [comment]
Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/rawl-0.2.0b1-py3.6.egg/rawl/__init__.py", line 53, in __enter__
        self.conn.set_session(isolation_level=ISOLATION_LEVEL_READ_COMMITTED)
    psycopg2.ProgrammingError: set_session cannot be used inside a transaction
